### ISSUE TITLE
Error  while running

### ISSUE THREAD

**Issue by RANV33R07** [Spidy20/Document_Scanner_Python#1]
ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
can you please solve this issue or tell me the steps so that I can use it

**Comment by HarshitMishra101** [comment]
in whole program change this

img = img.resize(new_size, Image.ANTIALIAS)

into this:

img = img.resize(new_size, Image.Resampling.LANCZOS)
